// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvfzLs71gr1SNqVBl6y_1j7e20znB068',
    appId: '1:920460640742:web:ec86eec8e1e82f47fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    authDomain: 'first-step-60186.firebaseapp.com',
    storageBucket: 'first-step-60186.firebasestorage.app',
    measurementId: 'G-43C1M7K9RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeuW6PYXUa-cfaOrM_0uRpMfXglZfEGUA',
    appId: '1:920460640742:android:f416ce3d81059b03fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    storageBucket: 'first-step-60186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdUHDmSnoW9ljSE1JK1UnHlouONVeH3I',
    appId: '1:920460640742:ios:57cb5d8b2fdff453fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    storageBucket: 'first-step-60186.firebasestorage.app',
    androidClientId: '920460640742-3is3qnf22959lkear57ne9fnmp90vrr9.apps.googleusercontent.com',
    iosClientId: '920460640742-ri7gqa4knta54smu25gh33jierlnj5i6.apps.googleusercontent.com',
    iosBundleId: 'com.firststep.firststepapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdUHDmSnoW9ljSE1JK1UnHlouONVeH3I',
    appId: '1:920460640742:ios:57cb5d8b2fdff453fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    storageBucket: 'first-step-60186.firebasestorage.app',
    androidClientId: '920460640742-3is3qnf22959lkear57ne9fnmp90vrr9.apps.googleusercontent.com',
    iosClientId: '920460640742-ri7gqa4knta54smu25gh33jierlnj5i6.apps.googleusercontent.com',
    iosBundleId: 'com.firststep.firststepapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEvfzLs71gr1SNqVBl6y_1j7e20znB068',
    appId: '1:920460640742:web:e2ce9a5c81e4e78cfad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    authDomain: 'first-step-60186.firebaseapp.com',
    storageBucket: 'first-step-60186.firebasestorage.app',
    measurementId: 'G-K35R8KSC6R',
  );
}
