// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvfzLs71gr1SNqVBl6y_1j7e20znB068',
    appId: '1:920460640742:web:76c8e1127f17ff11fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    authDomain: 'first-step-60186.firebaseapp.com',
    storageBucket: 'first-step-60186.firebasestorage.app',
    measurementId: 'G-C0GFRL1MR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeuW6PYXUa-cfaOrM_0uRpMfXglZfEGUA',
    appId: '1:920460640742:android:7eafb881925d1305fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    storageBucket: 'first-step-60186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdUHDmSnoW9ljSE1JK1UnHlouONVeH3I',
    appId: '1:920460640742:ios:93d21ef2c7d7bd00fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    storageBucket: 'first-step-60186.firebasestorage.app',
    androidClientId: '920460640742-564eecrrr5bgdet43rgthi2o458701ei.apps.googleusercontent.com',
    iosClientId: '920460640742-c44k04dloj5gdsnslm2794hlnp5nkcbv.apps.googleusercontent.com',
    iosBundleId: 'com.qader.firststep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdUHDmSnoW9ljSE1JK1UnHlouONVeH3I',
    appId: '1:920460640742:ios:93d21ef2c7d7bd00fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    storageBucket: 'first-step-60186.firebasestorage.app',
    androidClientId: '920460640742-564eecrrr5bgdet43rgthi2o458701ei.apps.googleusercontent.com',
    iosClientId: '920460640742-c44k04dloj5gdsnslm2794hlnp5nkcbv.apps.googleusercontent.com',
    iosBundleId: 'com.qader.firststep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEvfzLs71gr1SNqVBl6y_1j7e20znB068',
    appId: '1:920460640742:web:76c8e1127f17ff11fad627',
    messagingSenderId: '920460640742',
    projectId: 'first-step-60186',
    authDomain: 'first-step-60186.firebaseapp.com',
    storageBucket: 'first-step-60186.firebasestorage.app',
    measurementId: 'G-C0GFRL1MR8',
  );

}